export const categories = [
    "All Category",
    "Mobiles",
    "Electronics",
    "Vehicles",
    "Property",
    "Home Living",
    "Pets Animals",
    "Mens Fashion",
    "Womens Fashion",
    "Hobbies Sports Kids",
  ];

  export const locations = [
    "Dhaka",
    "Chittagong",
    "Sylhet",
    "Khulna",
    "Rajshahi",
    "Barisal",
    "Rangpur",
    "Mymensingh",
    "Comilla",
    "Narayanganj",
    "Gazipur",
    "Jessore",
    "Bogra",
    "Dinajpur",
    "Pabna",
    "Jamalpur",
    "Sherpur",
    "Netrokona",
    "Kishoreganj",
    "Manikganj",
    "Faridpur",
    "Kushtia",
    "Satkhira",
    "Tangail",
  ];
  